version: '3'
services:

  frontend:
    container_name: codebrick-test-frontend
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    image: codebrick-test-frontend
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/frontend

