version: '3'
services:

  frontend:
    container_name: codebrick-test-frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    image: codebrick-test-frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/frontend

